stages:
  - build

variables:
  DOCKER_BUILDKIT: "1"

publish_ndip_container:
  stage: build
  tags:
    - rse-multi-builder
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin "$CI_REGISTRY"
  script:
    - docker build --pull --file Dockerfile.ndip --tag "$CI_REGISTRY_IMAGE:ndip-$CI_COMMIT_SHA" --tag "$CI_REGISTRY_IMAGE:ndip" .
    - docker push "$CI_REGISTRY_IMAGE:ndip-$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:ndip"
  after_script:
    - docker logout "$CI_REGISTRY"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
