[unix_http_server]
file=/tmp/gsasii-supervisor.sock

[supervisord]
logfile=/tmp/gsasii-supervisord.log
logfile_maxbytes=20MB
logfile_backups=3
loglevel=info
pidfile=/tmp/gsasii-supervisord.pid
nodaemon=true
autorestart=false

[supervisorctl]
serverurl=unix:///tmp/gsasii-supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1600x1000x24 -nolisten tcp -noreset -ac
priority=10
autorestart=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:openbox]
command=/opt/gsasii-gui/run_openbox.sh
priority=20
autorestart=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:x11vnc]
command=/opt/gsasii-gui/run_x11vnc.sh
priority=20
autorestart=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:websockify]
command=/opt/conda/bin/websockify --heartbeat 30 6080 127.0.0.1:5900
priority=30
autorestart=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nginx]
command=/opt/gsasii-gui/run_nginx.sh
priority=40
autorestart=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:project_sync]
command=/opt/gsasii-gui/run_project_sync.sh
priority=45
autorestart=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:export_sync]
command=/opt/gsasii-gui/run_export_sync.sh
priority=45
autorestart=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:gsasii]
command=/opt/gsasii-gui/run_gsasii.sh
priority=50
autorestart=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[eventlistener:quit_on_service_exit]
command=/opt/gsasii-gui/run_exit_listener.sh
events=PROCESS_STATE_EXITED,PROCESS_STATE_FATAL
buffer_size=100
